In [1]:
import numpy as np
import pandas as pd
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split


In [4]:
import numpy as np
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
np.random.seed(42)
X_base=np.random.rand(200,1)*10
X=np.hstack([X_base+np.random.randn(200,1)*0.5,X_base*0.9+np.random.randn(200,1)*0.4,X_base*1.1+np.random.randn(200,1)*0.3,X_base+np.random.randn(200,1)*0.2,X_base*1.05+np.random.randn(200,1)*0.3,X_base*0.95+np.random.randn(200,1)*0.2,X_base*1.2+np.random.randn(200,1)*0.5])
true_w=np.array([3,-2,1,4,-1,2,0.5])
true_b=10
y=X.dot(true_w)+true_b+np.random.randn(200)*2
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
def ridge_regression_gd(X,y,lr=0.01,lam=0.1,epochs=1000):
    m,n=X.shape
    w=np.zeros(n)
    b=0
    X_mean=X.mean(axis=0)
    X_std=X.std(axis=0)
    X_norm=(X-X_mean)/X_std
    cost_history=[]
    for epoch in range(epochs):
        y_pred=X_norm.dot(w)+b
        error=y_pred-y
        dw=(1/m)*(X_norm.T.dot(error))+(lam/m)*w
        db=(1/m)*np.sum(error)
        w-=lr*dw
        b-=lr*db
        cost=(1/(2*m))*np.sum(error**2)+(lam/(2*m))*np.sum(w**2)
        if np.isnan(cost) or np.isinf(cost):break
        cost_history.append(cost)
    return w,b,cost_history,X_mean,X_std
def predict(X,w,b,X_mean,X_std):
    X_norm=(X-X_mean)/X_std
    return X_norm.dot(w)+b
learning_rates=[0.0001,0.001,0.01,0.1,1,10]
lambdas=[1e-15,1e-10,1e-5,1e-3,0,1,10,20]
best_config=None
best_r2=-np.inf
best_cost=np.inf
for lr in learning_rates:
    for lam in lambdas:
        w,b,cost_history,X_mean,X_std=ridge_regression_gd(X_train,y_train,lr=lr,lam=lam,epochs=1000)
        if len(cost_history)==0:continue
        y_pred=predict(X_test,w,b,X_mean,X_std)
        if np.any(np.isnan(y_pred)):continue
        r2=r2_score(y_test,y_pred)
        final_cost=cost_history[-1]
        if r2>best_r2 or (r2==best_r2 and final_cost<best_cost):
            best_config=(lr,lam,w,b)
            best_r2=r2
            best_cost=final_cost
        print(f"lr={lr}, lambda={lam:.1e}, Cost={final_cost:.4f}, R2={r2:.4f}")
best_lr,best_lambda,best_w,best_b=best_config
print("\nBest configuration found:")
print(f"Learning Rate: {best_lr}")
print(f"Regularization λ: {best_lambda}")
print(f"Best R2 Score: {best_r2:.4f}")
print(f"Final Cost: {best_cost:.4f}")


lr=0.0001, lambda=1.0e-15, Cost=997.8731, R2=-2.9682
lr=0.0001, lambda=1.0e-10, Cost=997.8731, R2=-2.9682
lr=0.0001, lambda=1.0e-05, Cost=997.8731, R2=-2.9682
lr=0.0001, lambda=1.0e-03, Cost=997.8732, R2=-2.9682
lr=0.0001, lambda=0.0e+00, Cost=997.8731, R2=-2.9682
lr=0.0001, lambda=1.0e+00, Cost=997.9669, R2=-2.9684
lr=0.0001, lambda=1.0e+01, Cost=998.8086, R2=-2.9698
lr=0.0001, lambda=2.0e+01, Cost=999.7374, R2=-2.9714
lr=0.001, lambda=1.0e-15, Cost=157.0229, R2=0.3749
lr=0.001, lambda=1.0e-10, Cost=157.0229, R2=0.3749
lr=0.001, lambda=1.0e-05, Cost=157.0229, R2=0.3749
lr=0.001, lambda=1.0e-03, Cost=157.0231, R2=0.3749
lr=0.001, lambda=0.0e+00, Cost=157.0229, R2=0.3749
lr=0.001, lambda=1.0e+00, Cost=157.2563, R2=0.3749
lr=0.001, lambda=1.0e+01, Cost=159.3380, R2=0.3742
lr=0.001, lambda=2.0e+01, Cost=161.6119, R2=0.3733
lr=0.01, lambda=1.0e-15, Cost=2.8089, R2=0.9888
lr=0.01, lambda=1.0e-10, Cost=2.8089, R2=0.9888
lr=0.01, lambda=1.0e-05, Cost=2.8089, R2=0.9888
lr=0.01, lambda=1.0e-03,

/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1275: RuntimeWarning: overflow encountered in square
  numerator = xp.sum(weight * (y_true - y_pred) ** 2, axis=0)
/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1275: RuntimeWarning: overflow encountered in square
  numerator = xp.sum(weight * (y_true - y_pred) ** 2, axis=0)
/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1275: RuntimeWarning: over

In [5]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
iris=load_iris()
X=iris.data
y=iris.target
sc=StandardScaler()
X=sc.fit_transform(X)
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
def sigmoid(z):return 1/(1+np.exp(-z))
def logistic_regression(X,y,lr=0.1,epochs=1000):
    m,n=X.shape
    w=np.zeros(n)
    b=0
    cost_history=[]
    for i in range(epochs):
        z=X.dot(w)+b
        y_pred=sigmoid(z)
        error=y_pred-y
        dw=(1/m)*X.T.dot(error)
        db=(1/m)*np.sum(error)
        w-=lr*dw
        b-=lr*db
        cost=-(1/m)*np.sum(y*np.log(y_pred+1e-9)+(1-y)*np.log(1-y_pred+1e-9))
        cost_history.append(cost)
    return w,b,cost_history
def predict_prob(X,w,b):return sigmoid(X.dot(w)+b)
classes=np.unique(y_train)
weights=[]
biases=[]
for c in classes:
    y_binary=(y_train==c).astype(int)
    w,b,_=logistic_regression(X_train,y_binary,lr=0.1,epochs=2000)
    weights.append(w)
    biases.append(b)
weights=np.array(weights)
biases=np.array(biases)
def predict(X,weights,biases):
    probs=[predict_prob(X,weights[i],biases[i]) for i in range(len(weights))]
    probs=np.array(probs).T
    return np.argmax(probs,axis=1)
y_pred=predict(X_test,weights,biases)
acc=accuracy_score(y_test,y_pred)
print("Accuracy:",acc)
print("Confusion Matrix:\n",confusion_matrix(y_test,y_pred))
print("Classification Report:\n",classification_report(y_test,y_pred))


Accuracy: 0.9666666666666667
Confusion Matrix:
 [[10  0  0]
 [ 0  8  1]
 [ 0  0 11]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.89      0.94         9
           2       0.92      1.00      0.96        11

    accuracy                           0.97        30
   macro avg       0.97      0.96      0.97        30
weighted avg       0.97      0.97      0.97        30

