Q1: Questions on Basic NumPy Array
(a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

In [ ]:
import numpy as np
arr=np.array([1,2,3,6,4])
rev= arr[::-1]
r= np.flip(arr)
r

array([4, 6, 3, 2, 1])

(b) Flatten the NumPy arr: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two
NumPy in-built methods

In [ ]:
import numpy as np
a=np.array([[1,2,3],[2,4,5],[1,2,3]])
fla=a.flatten()
fla

array([1, 2, 3, 2, 4, 5, 1, 2, 3])

(c) Compare the following numpy arrays:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

In [ ]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[1,2],[3,4]])
#print("compare", arr1==arr2)
print(np.array_equal(arr1,arr2))

True


(d) Find the most frequent value and their indice(s) in the following arrays:
i.
x = np.array([1,2,3,4,5,1,2,1,1,1]) ii.
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [3]:
import numpy as np
x=np.array([1,2,3,4,5,1,2,1,1,1])
y=np.array([1,1,1,2,3,4,2,4,3,3])
freq_x= np.bincount(x).argmax()
freq_y= np.bincount(y).argmax()
#using where to print only the values where it's true
print("i. most freq value:", freq_x, " index:", np.where(x==freq_x)[0])
print("ii. most freq value:", freq_y, "index:", np.where(y==freq_y)[0])

i. most freq value: 1  index: [0 5 7 8 9]
ii. most freq value: 1 index: [0 1 2]


(e) For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), find
i.
Sum of all elements
ii.Sum of all elements row-wise  
iii.Sum of all elements column-wise

In [4]:
import numpy as np
gfg= np.matrix('[4,1,9;12,3,1;4,5,6]')
print("i.", gfg.sum())
#row axis=1
print("ii.", gfg.sum(axis=1))
print("iii.", gfg.sum(axis=0))

i. 45
ii. [[14]
 [16]
 [15]]
iii. [[20  9 16]]


(f) For the matrix: n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]), find
i.
Sum of diagonal elements
ii.Eigen values of matrix
iii.Eigen vectors of matrix
iv.Inverse of matrix
v.Determinant of matrix

In [5]:
import numpy as np
n_array=np.array([[55,25,15],[30,44,2],[11,45,77]])
print("sum of diagonal el:", np.trace(n_array))
print("eigen val:", np.linalg.eigvals(n_array))
val,vec=np.linalg.eig(n_array)
print("eign vec:",vec)
print("inverse:",np.linalg.inv(n_array))
print("det:", np.linalg.det(n_array))

sum of diagonal el: 176
eigen val: [98.16835147 28.097044   49.73460452]
eign vec: [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
inverse: [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
det: 137180.0000000001


(g) Multiply the following matrices and also find covariance between matrices using NumPy:
i.
p = [[1, 2], [2, 3]]
q = [[4, 5], [6, 7]]
ii.
p = [[1, 2], [2, 3], [4, 5]]
q = [[4, 5, 1], [6, 7, 2]]

In [6]:
import numpy as np
p=np.array([[1,2],[2,3]])
q=np.array([[4,5],[6,7]])
p1=np.array([[1,2],[2,3],[4,5]])
q1=np.array([[4,5,1],[6,7,2]])
print("p*q=", np.dot(p,q))
print("p1*q1=", np.dot(p1,q1))
print("covariance of p:", np.cov(p.T))
print("covariance of q:", np.cov(q.T))
print("covariance of p1:", np.cov(p1.T))
print("covariance of q1:", np.cov(q1.T))

p*q= [[16 19]
 [26 31]]
p1*q1= [[16 19  5]
 [26 31  8]
 [46 55 14]]
covariance of p: [[0.5 0.5]
 [0.5 0.5]]
covariance of q: [[2. 2.]
 [2. 2.]]
covariance of p1: [[2.33333333 2.33333333]
 [2.33333333 2.33333333]]
covariance of q1: [[2.  2.  1. ]
 [2.  2.  1. ]
 [1.  1.  0.5]]


(h) For the matrices: x = np.array([[2, 3, 4], [3, 2, 9]]); y = np.array([[1, 5, 0], [5, 10, 3]]),
find inner, outer and cartesian product?

In [7]:
import numpy as np
x=np.array([[2,3,4],[3,2,9]])
y=np.array([[1,5,0],[5,10,3]])
print('inner:',np.inner(x,y))
print('outer:',np.outer(x.flatten(),y.flatten()))
print('cartesian:', np.array(np.meshgrid(x.flatten(), y.flatten())))

inner: [[17 52]
 [13 62]]
outer: [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
cartesian: [[[ 2  3  4  3  2  9]
  [ 2  3  4  3  2  9]
  [ 2  3  4  3  2  9]
  [ 2  3  4  3  2  9]
  [ 2  3  4  3  2  9]
  [ 2  3  4  3  2  9]]

 [[ 1  1  1  1  1  1]
  [ 5  5  5  5  5  5]
  [ 0  0  0  0  0  0]
  [ 5  5  5  5  5  5]
  [10 10 10 10 10 10]
  [ 3  3  3  3  3  3]]]


Q2: Based on NumPy Mathematics and Statistics
(a)
For the array: array = np.array([[1, -2, 3],[-4, 5, -6]])
i.Find element-wise absolute value
ii.Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each
row.
iii.Mean, Median and Standard Deviation of flattened array, of each column, and
each row

In [12]:
import numpy as np
arr=np.array([[1,-2,3],[-4,5,-6]])
print('absolute value:', np.abs(arr))
print('\n')
print('percentile of flattened array:', np.percentile(arr.flatten(),[25,50,76]))
print('percentile of each column:', np.percentile(arr,[25,50,76],axis=0))
print('percentile of each row:', np.percentile(arr,[25,50,76],axis=1))
print('\n')
print('mean,median,sd of:\nflattened array:', np.mean(arr.flatten()),np.median(arr.flatten()),np.std(arr.flatten()))
print('each column:', np.mean(arr,axis=0),np.median(arr,axis=0),np.std(arr,axis=0))
print('each row:', np.mean(arr,axis=1),np.median(arr,axis=1),np.std(arr,axis=1))

absolute value: [[1 2 3]
 [4 5 6]]


percentile of flattened array: [-3.5 -0.5  2.6]
percentile of each column: [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.2   3.32  0.84]]
percentile of each row: [[-0.5  -5.  ]
 [ 1.   -4.  ]
 [ 2.04  0.68]]


mean,median,sd of:
flattened array: -0.5 -0.5 3.8622100754188224
each column: [-1.5  1.5 -1.5] [-1.5  1.5 -1.5] [2.5 3.5 4.5]
each row: [ 0.66666667 -1.66666667] [ 1. -4.] [2.05480467 4.78423336]


(b)For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]). Find floor, ceiling
and truncated value, rounded values


In [13]:
import numpy as np
a=np.array([-1.8,-1.6,-0.5,0.5,1.6,1.8,3.0])
print('floor:', np.floor(a))
print('ceiling:', np.ceil(a))
print('trunc:', np.trunc(a))
print('round:', np.round(a))

floor: [-2. -2. -1.  0.  1.  1.  3.]
ceiling: [-1. -1. -0.  1.  2.  2.  3.]
trunc: [-1. -1. -0.  0.  1.  1.  3.]
round: [-2. -2. -0.  0.  2.  2.  3.]


Q3: Based on Searching and Sorting
(a) For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), find
i.
Sorted array
ii.Indices of sorted array
iii.4 smallest elements
iv.5 largest elements

In [16]:
import numpy as np
array=np.array([10,52,62,16,16,54,453])
print('sorted:', np.sort(array))
print('indices:', np.argsort(array))
#shuru ke 4, :4
print('4 smallest el:', np.sort(array)[:4])
#[::-1] se greatest pehle arhe
print('5 largest el:', np.sort(array)[-5:][::-1])

sorted: [ 10  16  16  52  54  62 453]
indices: [0 3 4 1 5 2 6]
4 smallest el: [10 16 16 52]
5 largest el: [453  62  54  52  16]


(b) For the array: array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]), find
i. Integer elements only
ii.Float elements only

In [17]:
import numpy as np
array=np.array([1.0,1.2,2.2,2.0,3.0,2.0])
print('integer:', array[array%1==0])
print('float:', array[array%1!=0])

integer: [1. 2. 3. 2.]
float: [1.2 2.2]
